# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Layerx < Formula
  desc "Terminal-based Docker image layer inspector"
  homepage "https://github.com/deveshctl/layerx"
  version "1.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deveshctl/layerx/releases/download/v1.6.1/layerx_darwin_amd64.tar.gz"
      sha256 "d7c2620f89c4a6ac75c35fe3078abcea565c20328898576e226f702244d84c5a"

      define_method(:install) do
        bin.install "layerx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deveshctl/layerx/releases/download/v1.6.1/layerx_darwin_arm64.tar.gz"
      sha256 "95511f312a48d9e4f8e115b89d9697d7aa4e34aecf6838e0c3d0bdf5d5f7cfae"

      define_method(:install) do
        bin.install "layerx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deveshctl/layerx/releases/download/v1.6.1/layerx_linux_amd64.tar.gz"
      sha256 "f724dfe8c8dbfff0b9ce29afc4683f093b653bcd16d1640c86524619fabdc807"
      define_method(:install) do
        bin.install "layerx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deveshctl/layerx/releases/download/v1.6.1/layerx_linux_arm64.tar.gz"
      sha256 "786b7815b87808ba88c8935bf900cab15a1d08818492a81708a6deadb94325a9"
      define_method(:install) do
        bin.install "layerx"
      end
    end
  end

  test do
    system "#{bin}/layerx", "--version"
  end
end
