# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Layerx < Formula
  desc "Terminal-based Docker image layer inspector"
  homepage "https://github.com/deveshpharswan/layerx"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deveshpharswan/layerx/releases/download/v1.0.0/layerx_1.0.0_darwin_amd64.tar.gz"
      sha256 "ded64823a52b3fab78910da963fa4bb4af40b852993c9c6d2b61b2d501d7fece"

      define_method(:install) do
        bin.install "layerx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deveshpharswan/layerx/releases/download/v1.0.0/layerx_1.0.0_darwin_arm64.tar.gz"
      sha256 "1c7294971a363018e634601f644f7c83b7ec5d4555c0005a246e4fe58ccbc15f"

      define_method(:install) do
        bin.install "layerx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deveshpharswan/layerx/releases/download/v1.0.0/layerx_1.0.0_linux_amd64.tar.gz"
      sha256 "6a4b1b3209b5ce5da9ebae3636905730079a102b51f3f2db2848c60061f2f99e"
      define_method(:install) do
        bin.install "layerx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deveshpharswan/layerx/releases/download/v1.0.0/layerx_1.0.0_linux_arm64.tar.gz"
      sha256 "394fb3377a04b3b4f3e98b55ebde7a1d6beb7432bc932782aedaa40bf51cd585"
      define_method(:install) do
        bin.install "layerx"
      end
    end
  end

  test do
    system "#{bin}/layerx", "--version"
  end
end
